### ISSUE TITLE
QvPlugin-Trojan-Go do not start.

### ISSUE THREAD

**Issue by luckyreny** [Qv2ray/QvPlugin-Trojan-Go#12]
We cannot find your Trojan-Go kernel. Please configure it in the plugin settings.
A plugin kernel failed to start. Please check the outbound settings.

**Comment by DuckSoft** [comment]
![img](https://user-images.githubusercontent.com/7822648/96412884-5dae7d00-121d-11eb-835a-f9ebfc35fb84.png)

**Comment by DuckSoft** [comment]
Read the fancy documentation before using:

https://github.com/Qv2ray/QvPlugin-Trojan-Go/blob/master/README.md#%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B
