### ISSUE TITLE
使用Shadowsocks AEAD进行二次加密提示这个，不知道那里出了问题？

### ISSUE THREAD

**Issue by Eliam520** [Qv2ray/QvPlugin-Trojan-Go#17]
如题使用Shadowsocks AEAD进行二次加密提示这个，不知道那里出了问题？谢谢。

![001](https://user-images.githubusercontent.com/63907602/105936995-a5039f80-608f-11eb-8911-7f396300b676.png)
![002](https://user-images.githubusercontent.com/63907602/105936998-a634cc80-608f-11eb-80ac-187d7435ba43.png)

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/105937294-3b37c580-6090-11eb-980f-d253a68cb17e.png)
![图片](https://user-images.githubusercontent.com/7822648/105937308-425ed380-6090-11eb-8fb0-b9f36466dcbd.png)
