### ISSUE TITLE
请问在qv2ray-2.7.0-pre2能用吗

### ISSUE THREAD

**Issue by GeorgeRudd** [Qv2ray/QvPlugin-Trojan-Go#18]
因为那里写了 Only for Qv2ray v2.7.0-pre1. NOT FOR Qv2ray v2.6.3 or v2.7.0-alpha1.想问问在qv2ray-2.7.0-pre2能用吗

**Comment by ghost** [comment]
@gcphym 可以

**Comment by GeorgeRudd** [comment]
谢谢
