### ISSUE TITLE
Qv2ray v2.6.2 疑在 macOS 10.14 下无法加载 Trojan-Go 插件

### ISSUE THREAD

**Issue by ChainZeaxion** [Qv2ray/QvPlugin-Trojan-Go#4]
macos cann't loading the plugin
windows can loading the plugin

MACOS 下该插件无法加载
Windows下该插件已可加载

**Comment by DuckSoft** [comment]
macOS 什么版本？Qv2ray 什么版本？macOS 用的插件的文件名是什么？无法加载的现象是什么？

**Comment by EpLiar** [comment]
可能是新版本 macOS 无法验证的开发者？

**Comment by ChainZeaxion** [comment]
> macOS 什么版本？Qv2ray 什么版本？macOS 用的插件的文件名是什么？无法加载的现象是什么？

MACOS-10.14.4 Qv2ray-2.6.2 Qv-Trojan-Go-v0.9.1
现象，拖入插件目录，关闭再重新打开主程序，手动新建配置，无对应Trojan-Go
打开主程序-插件，已加载插件项内，无Trojan-Go

**Comment by DuckSoft** [comment]
@ChainZeaxion 你是否记得从右键托盘完全退出 Qv2ray？或者在主界面按 Control+Q 完全退出再试？

**Comment by EpLiar** [comment]
完全重启一下 Qv2ray。
步骤可以是：
* dock 栏右键退出
* 主界面按下 Command+Q
* 顶部托盘退出

**Comment by ChainZeaxion** [comment]
> 完全重启一下 Qv2ray。
> 步骤可以是：
> 
> * dock 栏右键退出
> * 主界面按下 Command+Q
> * 顶部托盘退出

整机直接重启后打开，也是这个情况

**Comment by ghost** [comment]
Could you please provide the Qv2ray log?
By right clicking the log box and select "Qv2ray log"

**Comment by DuckSoft** [comment]
@U-v-U 已有另一位反应无法加载此插件于 macOS。
我们需要调研。

**Comment by ghost** [comment]
fixed, closing.

**Comment by ghost** [comment]
https://github.com/Qv2ray/QvPlugin-Trojan-Go/actions/runs/192268041
