### ISSUE TITLE
How to add Trojan-go kernel path? 

### ISSUE THREAD

**Issue by HowardWang-HT** [Qv2ray/QvPlugin-Trojan-Go#6]
如上标题，
Qv2ray中已按照文档添加Trojan-go的插件，但配置账号信息后，尝试启用，发现失败，提示没有Trojan-go kernel path无法启动。
请问接下来该如何？
感谢，盼复

**Comment by HowardWang-HT** [comment]
PS.  
<img width="988" alt="截屏2020-08-15 23 35 01" src="https://user-images.githubusercontent.com/41941258/90315874-62bb2b80-df51-11ea-923a-e10b47196c5e.png">

**Comment by DuckSoft** [comment]
你还要下载/安装 Trojan-Go 核心。
https://github.com/p4gefau1t/trojan-go/releases

**Comment by D414Dea4** [comment]
> 你还要下载/安装 Trojan-Go 核心。
> https://github.com/p4gefau1t/trojan-go/releases

我下载了最新的releases，解压后建了trojan-go文件夹，在Qv2ray里V2Ray核心可执行文件路径那里设置了解压后的exe，可以还是有问题，不知道哪里错了，请指教

**Comment by MarksonHon** [comment]
@D414Dea4 进群聊
https://t.me/qv2ray

**Comment by D414Dea4** [comment]
> @D414Dea4 进群聊
> https://t.me/qv2ray

今天下午入群回答错问题了。。。。。。。进不去了。。。。。。

**Comment by D414Dea4** [comment]
> 如上标题，
> Qv2ray中已按照文档添加Trojan-go的插件，但配置账号信息后，尝试启用，发现失败，提示没有Trojan-go kernel path无法启动。
> 请问接下来该如何？
> 感谢，盼复

请问你弄好了吗

**Comment by MarksonHon** [comment]
你还是看看插件的项目主页吧。
<https://github.com/Qv2ray/QvPlugin-Trojan-Go>
