### ISSUE TITLE
不支持WebSocket加密？

### ISSUE THREAD

**Issue by ArcheyChen** [Qv2ray/QvPlugin-Trojan-Go#8]
依照Trojan-GO的教程，开启WebSocket+Shadowsocks加密。
https://p4gefau1t.github.io/trojan-go/advance/websocket/
但是在客户端上，只有Websocket的选项，没有开关ss加密的选项。
自带的“加密”一栏中，填写任何东西都会造成Trojan-Go内核崩溃。
该怎么办呢

**Comment by ghost** [comment]
https://github.com/p4gefau1t/trojan-go/issues/132

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/59914293/93693465-c4634c80-fb32-11ea-903a-a9f18c9f579f.png)
